### ISSUE TITLE
Conditional PathfinderGoal

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Mobzy#57]
A pathfinder that would take a list of `GearyCondition`s and map of ints to other pathfinders.

If the conditions are met, try to run the pathfinders based on priority as defined by the map.

Syntax goal:
```yaml
goals:
  1: !<if>
    conditions:
      - !<health>
        within: 0..10
    run:
      1: !<mobzy:behaviour.throw_items> {}
      2: !<anothergoal> {}
```

Check out geary's `ConditionalAction` for a really similar example

P.S. if someone has a better name than `conditions` for the list of conditions, lemme know!
